version: '3.8'

services:
  backend:
    build: ./backend
    # ports:
      # - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:81
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-secret-pw
      - POSTGRES_DATABASE=postgres
  frontend:
    build: ./frontend
    # ports:
      # - 5000:5000
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my-secret-pw
  nginx:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

